# Generated by Django 3.2.6 on 2021-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='tweetDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mention',
            name='tweetID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
