# Generated by Django 3.2.6 on 2021-08-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiterapi', '0002_auto_20210808_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
