# Generated by Django 3.2.6 on 2021-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiterapi', '0003_mention_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='accountName',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='tweetID',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
