# Generated by Django 3.2.6 on 2021-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiterapi', '0005_auto_20210809_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
